Add a new discussion page
VocaDB/vocadb pull request #1531
Opened 2023-06-24 10:03 UTC by takahashi-akari

This PR introduces a new discussion page to the project.
Currently, it only includes the index page with a basic layout.

## Next steps
- Topic list page
- Topic page
- Features when logged in (start a conversation, leave a comment)

Please let me know if there are any changes needed or if you have any questions or concerns about this PR.
Thank you!

2023-06-24 11:25 UTC, FinnRG requested changes
Thank you very much for your effort. This already looks very good and I only have a few  minor suggestions for the code.

I've already deployed this branch to [https://vocadb-git-patch-discussion-index-page-finnrg.vercel.app/discussion](https://vocadb-git-patch-discussion-index-page-finnrg.vercel.app/), feel free to ping me after you've resolved these changes and I will redeploy so that users in the #development-talk channel can give their feedback on the layout.

2023-06-24 11:25 UTC, FinnRG commented on VocaDbWeb/New/components/Folder/Folder.styles.tsx
> +        padding: '10px',
Similarly you can use `theme.spacing.sm` instead of explicit pixel units here

2023-06-24 11:25 UTC, FinnRG commented on VocaDbWeb/New/pages/discussion/index.tsx
> +				Discussion
Typo: Discussions

2023-06-24 11:25 UTC, FinnRG commented on VocaDbWeb/New/components/Folder/Folder.tsx
> +				</Grid.Col>
Could you try using a paper (https://mantine.dev/core/paper/) as the base for folder? It has the withBorder and padding property, which should be a good fit for this use case. (But please keep the hover effect, I really like that)

Also span should be set to 6 if you want 2 folders per row.

2023-06-24 11:25 UTC, FinnRG commented on VocaDbWeb/New/components/Folder/Folder.tsx
> +                LastTopic: {new Date(folder.lastTopicDate).toLocaleString()} by {folder.lastTopicAuthor?.name}
Typo: Last topic

2023-06-24 11:25 UTC, FinnRG commented on VocaDbWeb/New/components/Folder/Folder.tsx
> +                <ThemeIcon variant="filled" style={{ display: "inline-flex", marginRight: "10px" }}><IconBook2 size="1rem" style={{ display: "inline-flex" }} /></ThemeIcon>{folder.name}
I'm not sure if display: "inline-flex" is necessary here? You can also set marginRight using the mr property (https://mantine.dev/styles/style-props/#supported-props)

2023-06-24 11:27 UTC, FinnRG commented
@takahashi-akari And also we use 4 spaces instead of tabs so please configure you editor/prettier that way.

2023-06-26 05:01 UTC, takahashi-akari commented
Thank you for your review. I have made the necessary changes and committed them.
Please review the updated changes.

Fix review comments in PR #1531
    
 - Use 'Paper' component
 - Use mantine theme colors
 - Fix typos
 - Replace spaces with tabs
 - Remove 'inline-flex'
 - Refactor code

2023-06-26 12:52 UTC, FinnRG requested changes
Thank you for these updates. I noticed a small layout bug in the mobile view:
![image](https://github.com/VocaDB/vocadb/assets/65015656/99904805-f56b-4de7-bf9f-3d63af5bfa77)

The last topic string increases the width of the card and disturbs the layout.

You can also post the link to the deployment (https://vocadb-git-patch-discussion-index-page-finnrg.vercel.app/discussion)  in the #development-talk channel and ask other people for general feedback on the layout.

2023-06-26 12:52 UTC, FinnRG commented on VocaDbWeb/New/components/Folder/Folder.styles.tsx
> +		backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0],
This can be removed

2023-06-26 12:52 UTC, FinnRG commented on VocaDbWeb/New/components/RecentTopic/RecentTopic.styles.tsx
> +		backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0],
This isn't needed

2023-06-26 12:52 UTC, FinnRG commented on VocaDbWeb/New/components/RecentTopic/RecentTopic.tsx
> +				</Grid.Col>
You only need one top level key on Grid.Col

2023-06-26 12:52 UTC, FinnRG commented on VocaDbWeb/New/components/Folder/Folder.tsx
> +				</Grid.Col>
You only need one top level key on Grid.Col

2023-06-26 12:52 UTC, FinnRG commented on VocaDbWeb/New/components/Folder/Folder.styles.tsx
> +	},
This can be one class

2023-06-26 13:47 UTC, takahashi-akari commented
Thank you for the re-review. I have fixed the points you mentioned and committed again. Please review once more and merge if everything is OK!
- Fix layout issues on smartphones
- Remove unnecessary background color
- Remove unnecessary keys
- Merge duplicate classes
- Reduce latency by using Promise.all

2023-06-26 13:51 UTC, FinnRG approved these changes

2023-06-26 13:51 UTC, merged